export class User{
name:string;
first:string;
last:string;
address:string;
city:string;
state:string;
country:string;
amount:string;
otherAmount:string;
zip:string;
phone:string;
email:string;
designation:string;
gift:string;
cardNumber:string;
expiryMonth:string;
expiryYear:string;
cvv:string;
card:string;
    constructor()
   {}
}